### ISSUE TITLE
What are the differences with DejaVu ? 

### ISSUE THREAD

**Issue by kursusHC** [Hoohaha/Auana-P#4]
Hi, 

Thanks for this project, it seems nice. I use DejaVu for an audio recognition software, could you sum up the differences between Auana and DejaVu ? Specifically for mic recording. 

Thank you

**Comment by Hoohaha** [comment]
Hi @kursusHC ,
The  most audio features are based on  frequency domain. However the major difference is fingerprints extraction for different algorithms. The some is fast, but is limited by accuracy. The some looks very well, but the robustness is not enough... Auana based on the theory of audio formant. Used a simple quantification method reduce much computations. So Auana is fast enough. The robustness also is pretty good.

Auana not support database yet. Because I think it should be light enough, so that we can use it by anywhere. The environment setup is very easy for user.

Mic recording: You can use the pyaudio to record, then put the data into Auana. You can refer to Demo_MicRecognition.py.
Thanks.

**Comment by kursusHC** [comment]
Thanks for the clarification !
